# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Based_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  Based_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  Based_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Based Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Based:
ifneq (,$(Based_config))
	@echo "==== Building Based ($(Based_config)) ===="
	@${MAKE} --no-print-directory -C Based -f Makefile config=$(Based_config)
endif

Sandbox: Based
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Based -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Based"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"