#pragma once

// From glfw3.h
#define BSD_MOUSE_BUTTON_1 0
#define BSD_MOUSE_BUTTON_2 1
#define BSD_MOUSE_BUTTON_3 2
#define BSD_MOUSE_BUTTON_4 3
#define BSD_MOUSE_BUTTON_5 4
#define BSD_MOUSE_BUTTON_6 5
#define BSD_MOUSE_BUTTON_7 6
#define BSD_MOUSE_BUTTON_8 7
#define BSD_MOUSE_BUTTON_LAST BSD_MOUSE_BUTTON_8
#define BSD_MOUSE_BUTTON_LEFT BSD_MOUSE_BUTTON_1
#define BSD_MOUSE_BUTTON_RIGHT BSD_MOUSE_BUTTON_2
#define BSD_MOUSE_BUTTON_MIDDLE BSD_MOUSE_BUTTON_3
